### ISSUE TITLE
reload! - undefined method

### ISSUE THREAD

**Issue by scottwater** [rweng/pry-rails#9]
Using pry-rails (0.1.2) causes reload! to no longer work in Rails 3.2. with Ruby 1.9.3. 

If I remove the pry-rails gem and use irb, it works as expected. 

Exact Message: 

  Loading development environment (Rails 3.2.0)
  [1] pry(main)> reload!
  NoMethodError: undefined method `reload!' for main:Object

Thanks,
Scott

P.S. I also noticed the app variable is no longer available.

**Comment by umuro** [comment]
if defined?(Rails) && Rails.env
  if defined?(Rails::ConsoleMethods)
    extend Rails::ConsoleMethods
  else
    def reload!(print=true)
      puts "Reloading..." if print
      ActionDispatch::Reloader.cleanup!
      ActionDispatch::Reloader.prepare!
      true
    end
  end
end

**Comment by juanpastas** [comment]
thanks @umuro .

**Comment by deadlyicon** [comment]
# .pryrc checked into my project root
```ruby
require 'rails/console/app'
include Rails::ConsoleMethods
```

**Comment by counterbeing** [comment]
that did the trick @deadlyicon :+1:

**Comment by deadlyicon** [comment]
![cheer](https://media.giphy.com/media/ppHVQrkpzSYpy/giphy.gif)
